baseURL = "https://ovojersey-index.vercel.app/"
languageCode = "en-us"
title = "OvoJersey Blog"
theme = "PaperMod"

[params]
  env = "production"
  description = "Football replica jerseys blog."
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML","RSS"]
